ALTER SESSION SET CONTAINER = XEPDB1;

CREATE tablespace COREFLOW
DATAFILE '/opt/oracle/oradata/XE/XEPDB1/COREFLOW.dbf' size 500m reuse
AUTOEXTEND ON NEXT 100m maxsize unlimited
SEGMENT SPACE MANAGEMENT AUTO;

CREATE USER COREFLOW_DB IDENTIFIED BY 1234
DEFAULT TABLESPACE COREFLOW
TEMPORARY TABLESPACE temp;

GRANT CONNECT, RESOURCE, UNLIMITED TABLESPACE TO COREFLOW_DB;

ALTER USER COREFLOW_DB QUOTA UNLIMITED ON COREFLOW;