  CREATE TABLE AI
(
    MODEL_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MODEL_NAME VARCHAR2(200),
    ACTIVE_STATUS CHAR(1) DEFAULT 'Y'
)SEGMENT CREATION IMMEDIATE 
LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);

CREATE TABLE AI_CHAT_HISTORY
(
    HISTORY_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_NO NUMBER,
    SESSION_ID NUMBER,
    "ROLE" VARCHAR2(50),
    "CONTENT" CLOB,
    CREATED_AT DATE DEFAULT SYSDATE
    )SEGMENT CREATION IMMEDIATE 
LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);

CREATE TABLE AI_CHAT_SESSION(
    SESSION_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_NO NUMBER,
    MODEL_ID NUMBER,
    TITLE VARCHAR2(300),
    CREATED_AT DATE DEFAULT SYSDATE,
    LAST_USED_AT DATE DEFAULT SYSDATE
    )SEGMENT CREATION IMMEDIATE 
LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);

CREATE TABLE AI_USAGE(
AI_USAGE_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_NO NUMBER,
    MODEL_ID NUMBER,
    CREATED_AT DATE DEFAULT SYSDATE,
    LAST_USED_AT DATE DEFAULT SYSDATE,
    TOKENS_USED NUMBER DEFAULT 0
    )SEGMENT CREATION IMMEDIATE 
LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);

CREATE TABLE AUTHROITY(
    USER_NO NUMBER,
    AUTHORITY VARCHAR2(50),
    CONSTRAINT PK_AUTHROITY PRIMARY KEY (USER_NO, AUTHORITY)
    )SEGMENT CREATION IMMEDIATE 
LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);

CREATE TABLE COMPANY_POLICY(
    POLICY_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TITLE VARCHAR2(200),
    CONTENT CLOB,
    CREATOR_USER_NO NUMBER,
    CREATED_AT DATE DEFAULT SYSDATE,
    MOD_USER_NO NUMBER,
    LAST_MODIFIED_AT DATE)SEGMENT CREATION IMMEDIATE 
LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
    
CREATE TABLE COMPANY_POLICY_MOD_HISTORY(
    MOD_HISTORY_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    POLICY_ID NUMBER,
    USER_NO NUMBER,
    MODIFIED_AT DATE DEFAULT SYSDATE,
    MOD_CONTENT CLOB)SEGMENT CREATION IMMEDIATE 
LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
    

CREATE TABLE DEPARTMENT(
    DEP_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DEP_NAME VARCHAR2(50))SEGMENT CREATION IMMEDIATE 
LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);


  CREATE TABLE MEMBER
(
   USER_NO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DEP_ID NUMBER,
    POS_ID NUMBER,
    EMAIL VARCHAR2(100),
    USER_NAME VARCHAR2(20),
    USER_PWD VARCHAR2(255),
    PHONE VARCHAR2(20),
    ADDRESS VARCHAR2(100),
    ADDRESS_DETAIL VARCHAR2(100),
    EXTENTION VARCHAR2(20),
    HIRE_DATE DATE DEFAULT SYSDATE,
    UPDATE_DATE DATE,
    STATUS CHAR(1) DEFAULT 'T'
)SEGMENT CREATION IMMEDIATE 
LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);


CREATE TABLE POSITIONS
(
    POS_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    POS_NAME VARCHAR2(50)
    )SEGMENT CREATION IMMEDIATE 
LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);