  CREATE TABLE "MEMBER"
(
   USER_NO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DEPT_ID NUMBER NOT NULL,
    POS_ID NUMBER NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL UNIQUE,
    USER_NAME VARCHAR2(20) NOT NULL,
    PHONE VARCHAR2(20) NOT NULL UNIQUE,
    ADDRESS VARCHAR2(100) NOT NULL,
    ADDRESS_DETAIL VARCHAR2(100) NOT NULL,
    EXTENTION VARCHAR2(20) UNIQUE,
    HIRE_DATE DATE DEFAULT SYSDATE NOT NULL,
    UPDATE_DATE DATE,
    STATUS CHAR(1) DEFAULT 'T' NOT NULL,
    
    CONSTRAINT FK_DEPARTMENT_DEPT FOREIGN KEY (DEPT_ID) REFERENCES "DEPARTMENT"(DEP_ID),
    CONSTRAINT FK_POSITIONS_POS FOREIGN KEY (POS_ID) REFERENCES "POSITIONS"(POS_ID)
)SEGMENT CREATION IMMEDIATE 
LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);